DROP TABLE IF EXISTS Mensaje
DROP TABLE IF EXISTS Participa;
DROP TABLE IF EXISTS Sala;
DROP TABLE IF EXISTS Multimedia;
DROP TABLE IF EXISTS HacenMatch;
DROP TABLE IF EXISTS VideoYoutube;
DROP TABLE IF EXISTS Usuario;
