name: Azure Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Enviar código a Azure
      - name: Send code to Azure
        env:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USERNAME }}
          key: ${{ secrets.AZURE_SSH_KEY }}
        run: |
          scp -r . username@host:/home/"${{ secrets.AZURE_USERNAME }}"/

      # Construir la imagen Docker
      - name: Build Docker image
        env:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USERNAME }}
          key: ${{ secrets.AZURE_SSH_KEY }}
        run: |
          ssh username@host "cd LoveRoomBackEnd && docker build -t loveroom ."

      # Ejecutar el contenedor Docker y reiniciar nginx
      - name: Run Docker container and restart nginx
        env:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USERNAME }}
          key: ${{ secrets.AZURE_SSH_KEY }}
        run: |
          ssh username@host "docker run -d --name loveroom_container -e DATABASE_URL='${{ secrets.DATABASE_URL }}' -e SECRET='${{ secrets.SECRET }}' loveroom && sudo systemctl restart nginx"


