name: Azure Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Enviar código a Azure
      - name: Send code to Azure
        env:
          key: ${{ secrets.AZURE_SSH_KEY }}
        run: scp -r . azureuser@40.121.163.248:/home/azureuser/

      # Construir la imagen Docker
      - name: Build Docker image
        env:
          key: ${{ secrets.AZURE_SSH_KEY }}
        run: |
          ssh "${{ secrets.AZURE_USERNAME }}@${{ secrets.AZURE_HOST }}" "cd LoveRoomBackEnd && docker build -t loveroom ."

      # Ejecutar el contenedor Docker y reiniciar nginx
      - name: Run Docker container and restart nginx
        env:
          key: ${{ secrets.AZURE_SSH_KEY }}
        run: |
          ssh "${{ secrets.AZURE_USERNAME }}@${{ secrets.AZURE_HOST }}" "docker run -d --name loveroom_container -e DATABASE_URL='${{ secrets.DATABASE_URL }}' -e SECRET='${{ secrets.SECRET }}' loveroom && sudo systemctl restart nginx"


