name: Docker Deployment

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t loveroom .

    - name: Save Docker image to file
      run: docker save loveroom > image.tar
      
    - name: Copy image to Azure VM
      run: scp -i ${{ secrets.AZURE_SSH_KEY }} image.tar ${{ secrets.AZURE_USER }}@${{ secrets.AZURE_HOST }}:/loveroom_images/image.tar

    - name: Load Docker image on Azure VM
      run: ssh -i ${{ secrets.AZURE_SSH_KEY }} ${{ secrets.AZURE_USER }}@${{ secrets.AZURE_HOST }} "docker load -i /loveroom_images/image.tar"

    - name: Run Docker container on Azure VM
      run: ssh -i ${{ secrets.AZURE_SSH_KEY }} ${{ secrets.AZURE_USER }}@${{ secrets.AZURE_HOST }} "docker run -d --name loveroom_container -e DATABASE_URL='${{ secrets.DATABASE_URL }}' -e SECRET='${{ secrets.SECRET }}' loveroom"
