name: Docker Deployment

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t loveroom --build-arg DATABASE_URL="${{ secrets.DATABASE_URL }}" --build-arg SECRET="${{ secrets.SECRET }}" .

    - name: Save Docker image to file
      run: docker save loveroom > image.tar

    - name: Setup SSH
      run: |
        echo "${{ secrets.AZURE_SSH_KEY }}" > ssh_key.pem
        chmod 600 ssh_key.pem

    - name: Copy image to Azure VM
      run: scp -i ssh_key.pem image.tar ${{ secrets.AZURE_USERNAME }}@${{ secrets.AZURE_HOST }}:/loveroom_images/image.tar

    - name: Load Docker image on Azure VM
      run: ssh -i ssh_key.pem ${{ secrets.AZURE_USERNAME }}@${{ secrets.AZURE_HOST }} "docker load -i /loveroom_images/image.tar"

    - name: Run Docker container on Azure VM
      run: ssh -i ssh_key.pem ${{ secrets.AZURE_USERNAME }}@${{ secrets.AZURE_HOST }} "docker run -d --name loveroom_container -e DATABASE_URL='${{ secrets.DATABASE_URL }}' -e SECRET='${{ secrets.SECRET }}' loveroom"
